backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "artikler"
    label: "Artikler"
    folder: "src/pages/artikler"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Dato", name: "date", widget: "datetime" }
      - { label: "Beskrivelse", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Innhold", name: "body", widget: "markdown" }
      - { label: "Tagger", name: "tags", widget: "list" }

  - name: "pages"
    label: "Sider"
    files:
      - file: "src/pages/index.md"
        label: "Forside"
        name: "index"
        fields:
          - { name: "templateKey", widget: "hidden", default: "index" }
          - { label: Tittel, name: title, widget: string }
          - { label: Bilde, name: image, widget: image }
          - { label: Beskrivelse, name: description, widget: string }
          - { label: Innhold, name: "body", widget: "markdown" }
      - file: "src/pages/program.md"
        label: "Program"
        name: "program"
        fields:
          - { name: "path", widget: "hidden", default: "/program" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/kontakt.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
          - { label: Tittel, name: title, widget: string }
          - { label: Beskrivelse, name: description, widget: string }
          - {
              label: Kontaktpersoner,
              name: contacts,
              widget: list,
              fields:
                [
                  { label: Navn, name: name, widget: string },
                  { label: Tittel, name: title, widget: string },
                  { label: "E-post", name: email, widget: string },
                  { label: Telefon, name: phone, widget: string },
                ],
            }
