backend:
  name: git-gateway
  branch: master

media_folder: /static/img/upload
public_folder: /img/upload

collections:
  - name: "artikler"
    label: "Artikler"
    folder: "src/pages/artikler"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "templateKey", widget: "hidden", default: "blog-post" }
      - { label: "Tittel", name: "title", widget: "string" }
      - { label: "Dato", name: "date", widget: "datetime" }
      - { label: "Beskrivelse", name: "description", widget: "text" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Innhold", name: "body", widget: "markdown" }
      - { label: "Tagger", name: "tags", widget: "list" }

  - name: "pages"
    label: "Sider"
    files:
      - file: "src/pages/index.md"
        label: "Forsiden"
        delete: false
        name: "index"
        fields:
          - { name: "templateKey", widget: "hidden", default: "index" }
          - { label: Tittel, name: title, widget: string }
          - { label: Bilde, name: image, widget: image }
          - { label: Beskrivelse, name: description, widget: string }
          - {
              label: Kontaktpersoner,
              name: contacts,
              widget: list,
              fields:
                [
                  { label: Navn, name: name, widget: string },
                  { label: Tittel, name: title, widget: string },
                  { label: "E-post", name: email, widget: string },
                  { label: Telefon, name: phone, widget: string },
                ],
            }
          - { label: "Instagram brukernavn", name: instagram, widget: string }

      - file: "src/pages/info.md"
        label: "Informasjon"
        name: "info"
        delete: false
        fields:
          - { label: Tittel, name: "title", widget: "string" }
          - { label: Bilde, name: image, widget: image }
          - { label: Beskrivelse, name: description, widget: string }
          - { label: "Innhold", name: "body", widget: "markdown" }

      - file: "src/pages/bli-speider.md"
        label: "Bli speider"
        name: "bli-speider"
        delete: false
        fields:
          - { label: Tittel, name: "title", widget: "string" }
          - { label: Bilde, name: image, widget: image }
          - { label: Beskrivelse, name: description, widget: string }
          - { label: "Innhold", name: "body", widget: "markdown" }
